version: '3'
services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      -  80:80
    volumes:
      - .:/var/www/html
    links:
      - 'mariadb'

  mariadb:
    container_name: docker-mysql
    restart: always
    ports:
      - 3306:3306
    build:
      context: ./mariadb
    environment:
      TZ: "Europe/Kyiv"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'pzubar'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'camagru'

volumes:
  mariadb: