version: '3'
services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      -  80:80
    volumes:
      - .:/var/www/html
    links:
      - 'mariadb'

  mariadb:
    container_name: docker-mysql
    restart: always
    ports:
      - 3306:3306
    build:
      context: ./mariadb
    environment:
      TZ: "Europe/Kyiv"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'pzubar'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'camagru'

volumes:
  mariadb:

    # Backup
# docker exec CONTAINER /usr/bin/mysqldump -u root --password=root DATABASE > backup.sql
# docker exec docker-mysql /usr/bin/mysqldump -u root --password=rootpwd camagru > backup.sql

    # Restore
#    cat backup.sql | docker exec -i CONTAINER /usr/bin/mysql -u root --password=root DATABASE